repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-format
        name: poetry run ruff format
      # - id: ruff
      #   name: poetry run ruff check and fix
      #   args: ["--fix"]