[project]
name = "monitor-jobs"
version = "0.9.0"
description = "Cloud Run cron jobs and scrapers to support monitor"
authors = [
    {name = "SkyTruth"}
]
readme = "README.md"
requires-python = ">=3.10"
# TODO: Once we finish testing and deploying jobs, let's pin these dependencies to their final versions.
dependencies = [
    "requests >=2.32.3",
    "python-dateutil >=2.9.0.post0",
    "urllib3 >=1.26.19",
    "beautifulsoup4 >=4.12.3",
    "lxml >=5.3.0",
    "itemloaders >=1.0.3",
    "scrapy >=2.11.2",
    "jinja2 >=3.1.4",
    "selenium >=3.141.0",
    "rasterio >=1.3.9",
    "google-api-python-client >=2.137.0",
    "google-crc32c >=1.3.0",
    "oauth2client >=4.1.3",
    "psycopg2-binary >=2.9.10",
    "numpy >=1.24.4",
    "google-cloud-secret-manager >=2.11.1",
    "google-cloud-storage (>=3.7.0,<4.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "xlrd (>=2.0.2,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.2"
pre-commit = "^4.3.0"
ipykernel = "^7.1.0"

[tool.poetry]
package-mode = false

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select=["E", "F", "UP", "B", "SIM", "I"]
ignore=["SIM115", "B007", "SIM118", "E741", "SIM105", "SIM108", "E711", "E722"]

[tool.pytest.ini_options]
pythonpath = ["src"]
