# Mapping for NRC scraper. This avoids using database tables for processing data.
FIELD_MAP = {
    "reportnum": {
        "sheet_name": "CALLS",
        "column": "SEQNOS",
    },
    "calltype": {
        "sheet_name": "CALLS",
        "column": "CALLTYPE",
    },
    "suspected_responsible_company": {
        "sheet_name": "CALLS",
        "column": "RESPONSIBLE_COMPANY",
    },
    "description": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "DESCRIPTION_OF_INCIDENT",
    },
    "incident_datetime": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "INCIDENT_DATE_TIME",
    },
    "incidenttype": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "TYPE_OF_INCIDENT",
    },
    "cause": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "INCIDENT_CAUSE",
    },
    "incidentlocation": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "INCIDENT_LOCATION",
    },
    "location": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_ADDRESS",
    },
    "locationstreet1": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_STREET1",
    },
    "locationstreet2": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_STREET2",
    },
    "state": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_STATE",
    },
    "nearestcity": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_NEAREST_CITY",
    },
    "county": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_COUNTY",
    },
    "medium_affected": {
        "sheet_name": "INCIDENT_DETAILS",
        "column": "MEDIUM_DESC",
    },
    "material_name": {
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "NAME_OF_MATERIAL",
    },
    "reached_water": {
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "IF_REACHED_WATER",
    },
    "amt_in_water": {
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "AMOUNT_IN_WATER",
    },
    "amt_in_water_unit": {
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "UNIT_OF_MEASURE_REACH_WATER",
    },
    "chris_code": {
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "CHRIS_CODE",
    },
    "amount": {
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "AMOUNT_OF_MATERIAL",
    },
    "unit": {
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "UNIT_OF_MEASURE",
    },
    "ft_id": {
        "sheet_name": "CALLS",
        "column": None,
    },
    "st_id": {
        "sheet_name": "CALLS",
        "column": None,
    },
    "full_report_url": {
        "sheet_name": "CALLS",
        "column": None,
    },
    "materials_url": {
        "sheet_name": "CALLS",
        "column": None,
    },
    "time_stamp": {
        "sheet_name": "CALLS",
        "column": None,
    },
    "lat_degrees": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_DEG",
    },
    "lat_minutes": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_MIN",
    },
    "lat_seconds": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_SEC",
    },
    "lat_quadrant": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_QUAD",
    },
    "lon_degrees": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_DEG",
    },
    "lon_minutes": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_MIN",
    },
    "lon_seconds": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_SEC",
    },
    "lon_quadrant": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_QUAD",
    },
    "zip": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_ZIP",
    },
    "sheen_size_length": {
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_LENGTH",
    },
    "sheen_size_width": {
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_WIDTH",
    },
    "sheen_size_width_unit": {
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_WIDTH_UNITS",
    },
    "sheen_size_length_unit": {
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_LENGTH_UNITS",
    },
    "affected_area": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": None,
    },
    "task_id": {
        "sheet_name": "INCIDENT_COMMONS",
        "column": "SEQNOS",
    },
}


TERRITORIES = {
    "AL": "Alabama",
    "KY": "Kentucky",
    "OH": "Ohio",
    "AK": "Alaska",
    "LA": "Louisiana",
    "OK": "Oklahoma",
    "AZ": "Arizona",
    "ME": "Maine",
    "OR": "Oregon",
    "AR": "Arkansas",
    "MD": "Maryland",
    "PA": "Pennsylvania",
    "AS": "American Samoa",
    "MA": "Massachusetts",
    "PR": "Puerto Rico",
    "CA": "California",
    "MI": "Michigan",
    "RI": "Rhode Island",
    "CO": "Colorado",
    "MN": "Minnesota",
    "SC": "South Carolina",
    "CT": "Connecticut",
    "MS": "Mississippi",
    "SD": "South Dakota",
    "DE": "Delaware",
    "MO": "Missouri",
    "TN": "Tennessee",
    "DC": "District of Columbia",
    "MT": "Montana",
    "TX": "Texas",
    "FL": "Florida",
    "NE": "Nebraska",
    "TT": "Trust Territories",
    "GA": "Georgia",
    "NV": "Nevada",
    "UT": "Utah",
    "GU": "Guam",
    "NH": "New Hampshire",
    "VT": "Vermont",
    "HI": "Hawaii",
    "NJ": "New Jersey",
    "VA": "Virginia",
    "ID": "Idaho",
    "NM": "New Mexico",
    "VI": "Virgin Islands",
    "IL": "Illinois",
    "NY": "New York",
    "WA": "Washington",
    "IN": "Indiana",
    "NC": "North Carolina",
    "WV": "West Virginia",
    "IA": "Iowa",
    "ND": "North Dakota",
    "WI": "Wisconsin",
    "KS": "Kansas",
    "MP": "Northern Mariana Islands",
    "WY": "Wyoming",
}

RELEASE_TYPE_DICT = {
    "OIL: CRUDE": "oil",
    "CONDENSATE": "oil",
    "UNKNOWN OIL": "oil",
    "GASOLINE": "fuel",
    "OIL: DIESEL": "fuel",
    "OIL, FUEL: ": "fuel",
    "JET FUEL": "fuel",
    "FUEL OIL": "fuel",
    "HYDRAULIC": "mechanical",
    "OIL, MISC: LUBRICATING": "mechanical",
    "TRANSMISSION FLUID": "mechanical",
    "OIL, MISC: MOTOR": "mechanical",
    "OIL, MISC: TRANSFORMER": "mechanical",
}

UNIT_CONVERSIONS = {
    r"METER": ("FEET", 3.2808399),
    r"MILE": ("FEET", 5280),
    r"Y": ("FEET", 3),
    r"INCH": ("FEET", 0.083333333333),
    r"KILOMETER": ("FEET", 3280.8399),
    r"F": ("FEET", 1),
    r"`[\s]*FEET": ("FEET", 1),
    r"GALLON": ("GALLON", 1),
    r"BARREL": ("GALLON", 42),
    r"TEASPOON": ("GALLON", 0.00130208333),
    r"TABLESPOON": ("GALLON", 0.00390625),
    r"CUP": ("GALLON", 0.0625),
    r"PINT": ("GALLON", 0.125),
    r"QUART": ("GALLON", 0.25),
    r"LITER": ("GALLON", 0.264172052358),
    r"CUBIC METER": ("GALLON", 264.172052),
    r"CUBIC YARD": ("GALLON", 201.974026),
    r"CUBIC F[EO][EO]T": ("CUBIC FT", 1),
    r"DROP": ("GALLON", 1.71321916083e-05),
    r"OUNCE": ("POUND", 0.0625),
    r"POUND": ("POUND", 1),
    r"TON": ("POUND", 2000),
    r"GRAM": ("POUND", 0.00220462262),
    r"EACH": ("EACH", 1),
    r"OTHER": ("OTHER", 1),
    r"PART\(S\) PER MILLION": ("PART(S) PER MILLION", 1),
    r"MIL CBF": ("MIL CBF", 1),
    r"MCF": ("MCF", 1),
    r"MMCF": ("MMCF", 1),
    r"MILCURIE": ("MILCURIE(S)", 1),
    r"CURIE": ("CURIE", 1),
    r"UNK": ("UNKNOWN", 1),
    r"UKN": ("UNKNOWN", 1),
    r"N/A": ("NONE", 1),
    r"NONE": ("NONE", 1),
}

STANDARD_UNITS = {
    "FEET",
    "GALLON",
    "POUND",
    "CUBIC FT",
    "ACRES",
    "SQ. FT.",
    "MILES",
    "EACH",
    "NONE",
    "UNKNOWN",
    "MCF",
    "MMCF",
    "MIL CBF",
    "CURIE",
    "MILCURIE(S)",
    "PART(S) PER MILLION",
}
