# Mapping for NRC scraper. This avoids using database tables for processing data.
FIELD_MAP = [
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "reportnum",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": "SEQNOS",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "calltype",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": "CALLTYPE",
        "processing": {"function": "NrcScrapedReportFields.calltype"},
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "suspected_responsible_company",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": "RESPONSIBLE_COMPANY",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "description",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "DESCRIPTION_OF_INCIDENT",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "incident_datetime",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "INCIDENT_DATE_TIME",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "incidenttype",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "TYPE_OF_INCIDENT",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "cause",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "INCIDENT_CAUSE",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "incidentlocation",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "INCIDENT_LOCATION",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "location",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_ADDRESS",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "locationstreet1",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_STREET1",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "locationstreet2",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_STREET2",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "state",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_STATE",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "nearestcity",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_NEAREST_CITY",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "county",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_COUNTY",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "medium_affected",
        "db_schema": "public",
        "sheet_name": "INCIDENT_DETAILS",
        "column": "MEDIUM_DESC",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "material_name",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "NAME_OF_MATERIAL",
        "processing": None,
    },
    {
        "db_table": "NrcScrapedMaterial",
        "db_field": "reportnum",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "SEQNOS",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "name",
        "db_field_width": 128,
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "NAME_OF_MATERIAL",
        "processing": None,
    },
    {
        "db_table": "NrcScrapedMaterial",
        "db_field": "reached_water",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "IF_REACHED_WATER",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "amt_in_water",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "AMOUNT_IN_WATER",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "amt_in_water_unit",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "UNIT_OF_MEASURE_REACH_WATER",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "chris_code",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "CHRIS_CODE",
        "processing": None,
    },
    {  # TODO: Not populated
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "amount",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "AMOUNT_OF_MATERIAL",
        "processing": None,
    },
    {  # TODO: Not populated
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "unit",
        "db_schema": "public",
        "sheet_name": "MATERIAL_INVOLVED",
        "column": "UNIT_OF_MEASURE",
        "processing": None,
    },
    {
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "ft_id",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": None,
        "processing": {"function": "NrcScrapedMaterialFields.ft_id"},
    },
    {
        "db_table": '"NrcScrapedMaterial"',
        "db_field": "st_id",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": None,
        "processing": {"function": "NrcScrapedMaterialFields.st_id"},
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "full_report_url",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": None,
        "processing": {"function": "NrcScrapedReportFields.full_report_url"},
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "materials_url",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": None,
        "processing": {"function": "NrcScrapedReportFields.materials_url"},
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "time_stamp",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": None,
        "processing": {"function": "NrcScrapedReportFields.time_stamp"},
    },
    {
        "db_table": '"NrcScrapedReport"',
        "db_field": "ft_id",
        "db_schema": "public",
        "sheet_name": "CALLS",
        "column": None,
        "processing": {"function": "NrcScrapedReportFields.ft_id"},
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "reportnum",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "SEQNOS",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lat_degrees",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_DEG",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lat_minutes",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_MIN",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lat_seconds",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_SEC",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lat_quadrant",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LAT_QUAD",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lon_degrees",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_DEG",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lon_minutes",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_MIN",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lon_seconds",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_SEC",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "lon_quadrant",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LONG_QUAD",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "zip",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_ZIP",
        "processing": None,
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "sheen_size_length",
        "db_schema": "public",
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_LENGTH",
        "processing": {
            "function": "NrcParsedReportFields.sheen_size_length",
            "args": {"unit_field": "SHEEN_SIZE_LENGTH_UNITS"},
        },
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "sheen_size_width",
        "db_schema": "public",
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_WIDTH",
        "processing": {
            "function": "NrcParsedReportFields.sheen_size_width",
            "args": {"unit_field": "SHEEN_SIZE_WIDTH_UNITS"},
        },
    },
    {
        "db_table": None,
        "db_field": "sheen_size_width_unit",
        "db_schema": "public",
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_WIDTH_UNITS",
        "processing": None,
    },
    {
        "db_table": None,
        "db_field": "sheen_size_length_unit",
        "db_schema": "public",
        "sheet_name": "INCIDENT_DETAILS",
        "column": "SHEEN_SIZE_LENGTH_UNITS",
        "processing": None,
    },
    {  # TODO: Implement
        "db_table": '"NrcParsedReport"',
        "db_field": "affected_area",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": None,
        "processing": {"function": "NrcParsedReportFields.affected_area"},
    },
    {
        "db_table": '"NrcParsedReport"',
        "db_field": "county",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "LOCATION_COUNTY",
        "processing": None,
    },
    {
        "db_table": '"BotTaskStatus"',
        "db_field": "task_id",
        "db_schema": "public",
        "sheet_name": "INCIDENT_COMMONS",
        "column": "SEQNOS",
        "processing": None,
    },
]

TERRITORIES = {
    "AL": "Alabama",
    "KY": "Kentucky",
    "OH": "Ohio",
    "AK": "Alaska",
    "LA": "Louisiana",
    "OK": "Oklahoma",
    "AZ": "Arizona",
    "ME": "Maine",
    "OR": "Oregon",
    "AR": "Arkansas",
    "MD": "Maryland",
    "PA": "Pennsylvania",
    "AS": "American Samoa",
    "MA": "Massachusetts",
    "PR": "Puerto Rico",
    "CA": "California",
    "MI": "Michigan",
    "RI": "Rhode Island",
    "CO": "Colorado",
    "MN": "Minnesota",
    "SC": "South Carolina",
    "CT": "Connecticut",
    "MS": "Mississippi",
    "SD": "South Dakota",
    "DE": "Delaware",
    "MO": "Missouri",
    "TN": "Tennessee",
    "DC": "District of Columbia",
    "MT": "Montana",
    "TX": "Texas",
    "FL": "Florida",
    "NE": "Nebraska",
    "TT": "Trust Territories",
    "GA": "Georgia",
    "NV": "Nevada",
    "UT": "Utah",
    "GU": "Guam",
    "NH": "New Hampshire",
    "VT": "Vermont",
    "HI": "Hawaii",
    "NJ": "New Jersey",
    "VA": "Virginia",
    "ID": "Idaho",
    "NM": "New Mexico",
    "VI": "Virgin Islands",
    "IL": "Illinois",
    "NY": "New York",
    "WA": "Washington",
    "IN": "Indiana",
    "NC": "North Carolina",
    "WV": "West Virginia",
    "IA": "Iowa",
    "ND": "North Dakota",
    "WI": "Wisconsin",
    "KS": "Kansas",
    "MP": "Northern Mariana Islands",
    "WY": "Wyoming",
}

RELEASE_TYPE_DICT = {
    "OIL: CRUDE": "oil",
    "CONDENSATE": "oil",
    "UNKNOWN OIL": "oil",
    "GASOLINE": "fuel",
    "OIL: DIESEL": "fuel",
    "OIL, FUEL: ": "fuel",
    "JET FUEL": "fuel",
    "FUEL OIL": "fuel",
    "HYDRAULIC": "mechanical",
    "OIL, MISC: LUBRICATING": "mechanical",
    "TRANSMISSION FLUID": "mechanical",
    "OIL, MISC: MOTOR": "mechanical",
    "OIL, MISC: TRANSFORMER": "mechanical",
}

UNIT_CONVERSIONS = {
    r"METER": ("FEET", 3.2808399),
    r"MILE": ("FEET", 5280),
    r"Y": ("FEET", 3),
    r"INCH": ("FEET", 0.083333333333),
    r"KILOMETER": ("FEET", 3280.8399),
    r"F": ("FEET", 1),
    r"`[\s]*FEET": ("FEET", 1),
    r"GALLON": ("GALLON", 1),
    r"BARREL": ("GALLON", 42),
    r"TEASPOON": ("GALLON", 0.00130208333),
    r"TABLESPOON": ("GALLON", 0.00390625),
    r"CUP": ("GALLON", 0.0625),
    r"PINT": ("GALLON", 0.125),
    r"QUART": ("GALLON", 0.25),
    r"LITER": ("GALLON", 0.264172052358),
    r"CUBIC METER": ("GALLON", 264.172052),
    r"CUBIC YARD": ("GALLON", 201.974026),
    r"CUBIC F[EO][EO]T": ("CUBIC FT", 1),
    r"DROP": ("GALLON", 1.71321916083e-05),
    r"OUNCE": ("POUND", 0.0625),
    r"POUND": ("POUND", 1),
    r"TON": ("POUND", 2000),
    r"GRAM": ("POUND", 0.00220462262),
    r"EACH": ("EACH", 1),
    r"OTHER": ("OTHER", 1),
    r"PART\(S\) PER MILLION": ("PART(S) PER MILLION", 1),
    r"MIL CBF": ("MIL CBF", 1),
    r"MCF": ("MCF", 1),
    r"MMCF": ("MMCF", 1),
    r"MILCURIE": ("MILCURIE(S)", 1),
    r"CURIE": ("CURIE", 1),
    r"UNK": ("UNKNOWN", 1),
    r"UKN": ("UNKNOWN", 1),
    r"N/A": ("NONE", 1),
    r"NONE": ("NONE", 1),
}

STANDARD_UNITS = {
    "FEET",
    "GALLON",
    "POUND",
    "CUBIC FT",
    "ACRES",
    "SQ. FT.",
    "MILES",
    "EACH",
    "NONE",
    "UNKNOWN",
    "MCF",
    "MMCF",
    "MIL CBF",
    "CURIE",
    "MILCURIE(S)",
    "PART(S) PER MILLION",
}
