# Builds and pushes the shared image all jobs will use

substitutions:
  _REPO: monitor-jobs
  _IMAGE_NAME: jobs

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: Build Docker Image
    id: "Build"
    args:
      - "build"
      - "-t"
      - "us-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA"
      - "-t"
      - "us-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest"
      - "."

  - name: Push Docker - tag SHA
    id: "Push"
    args:
      - "push"
      - "us-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA"

  - name: Push Docker - tag latest
    id: "Push latest"
    args:
      - "push"
      - "us-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest"

images:
  - "us-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA"
  - "us-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest"