name: Deploy Jobs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/33114313460/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: "github-deployer@your-project.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: your-project-id

      - name: Submit Cloud Build
        run: |
          gcloud builds submit \
            --config infrastructure.cloudbuil.image.yaml \

  deploy-email-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/33114313460/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: "github-deployer@your-project.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: your-project-id

      - name: Submit Cloud Build
        run: |
          gcloud builds submit \
            --config infrastructure.email_alerts.cloudbuild.job.email_alerts.yaml \
  
  deploy-email-alerts-scheduler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/33114313460/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: "github-deployer@your-project.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: your-project-id

      - name: Submit Cloud Build
        run: |
          gcloud builds submit \
            --config infrastructure.email_alerts.cloudbuild.scheduler.email_alerts.yaml \