name: Deploy Cloud Scheduler

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
      scheduler_name:
        required: true
        type: string
      schedule:
        required: true
        type: string                # e.g. "0 13 * * *"
      cb_scheduler_path:
        required: false
        type: string
        default: infrastructure/cloudbuild.scheduler.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: skytruth-alerts2
          workload_identity_provider: "projects/33114313460/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: "github-deployer@skytruth-alerts2.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: skytruth-alerts2

      - name: Submit Cloud Build (Scheduler)
        run: |
          echo "deploy - '${{ inputs.schedule }}'_SCHEDULER_NAME=${{ inputs.scheduler_name }}'"
          gcloud builds submit \
            --config "${{ inputs.cb_scheduler_path }}" \
            --substitutions=_SCHEDULE=${{ inputs.schedule }},_SCHEDULER_NAME=${{ inputs.scheduler_name }},_JOB_NAME=${{ inputs.job_name }}